version: '3.9'
services:
    redis:
        image: redis:alpine
        container_name: redis
        command: redis-server --appendonly yes
        volumes:
            - ./database:/data
        ports:
            - 6380:6379
