version: '3.9'
services:
    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - 6379:6379
        expose:
            - 6379
    back-end:
        image: olimungo/geek-back-end
        container_name: geek-back-end
        build: ./back-end
        ports:
            - 9000:9000
        environment:
            - NODE_ENV=production
            - REDIS_URL=redis://redis
            - CORS_ORIGIN=http://192.168.178.36:3000, http://pi.local:3000

    front-end:
        image: olimungo/geek-front-end
        container_name: geek-front-end
        build: ./front-end
        ports:
            - 80:80
        environment:
            - NODE_ENV=production
